version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/hr_db
      - LLM_URL=http://llm-service:5000
      - LANGFUSE_PUBLIC_KEY=dev_public_key
      - LANGFUSE_SECRET_KEY=dev_secret_key
      - LANGFUSE_HOST=http://langfuse:3000
    depends_on:
      - db
      - llm-service
      - langfuse

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hr_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  llm-service:
    build: ./llm-service
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_API=http://host.docker.internal:11434
    volumes:
      - ./llm-service:/app
    restart: unless-stopped

  jupyter:
    image: jupyter/minimal-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./llm-service/notebooks:/home/jovyan/work
    depends_on:
      - llm-service

volumes:
  pgdata:
